### ISSUE TITLE
DESCRIPTOR should be an absolute path

### ISSUE THREAD

**Issue by by2coffee** [v4lk/keyboard-gadget#1]
A very minor "error"; from the script it seems that DESCRIPTOR can point to .bin location relative to the script
`DESCRIPTOR=./keyboard-descriptor.bin`
But, we cd into /config/usb_gadget/keyboardgadget initially, so it must be an absolute path.

Thanks for the script, very well documented example to get started with configfs HID gadget :+1:

**Comment by qlyoung** [comment]
Changed to absolute path. thanks for bringing this issue to my attention : )

**Comment by by2coffee** [comment]
Wonderful, thanks!
